export const LOAD_TECHS = 'LOAD_TECHS';
export const LOAD_COMMENTS = 'LOAD_COMMENTS';
export const LOAD_LIKES = 'LOAD_LIKES';
export const LOAD_USERS = 'LOAD_USERS';
export const LOAD_USERTECHS = 'LOAD_USERTECHS';

export const INSERT_TECH = 'INSERT_TECH';
export const INSERT_COMMENT = 'INSERT_COMMENT';

export const UPDATE_LIKES = 'UPDATE_LIKES';
export const UPDATE_USERTECHS = 'UPDATE_USERTECHS';
export const DELETE_USERTECH = 'DELETE_USERTECH';
